#!/usr/bin/env sh

## By default it will try to update the database
## Every Tuesday, Thursday, and Sunday at 10:00.
JOB_SCHEDULE=${JOB_SCHEDULE:-"0 10 * * 2,4,7"}
MAXMIND_PRODUCTS=${MAXMIND_PRODUCTS:-"GeoLite2-City"}

mkdir -p /usr/local/etc/
cat <<GeoIP > /usr/local/etc/GeoIP.conf
AccountID ${MAXMIND_ACCOUNT}
LicenseKey ${MAXMIND_KEY}
EditionIDs ${MAXMIND_PRODUCTS}
DatabaseDirectory /etc/nginx/geoip
GeoIP

crontab - <<Task
${JOB_SCHEDULE} geoipupdate -v >> /var/log/cron.log 2>&1
Task

mkdir -p /etc/nginx/geoip && geoipupdate -v
mv `ls /etc/nginx/geoip/*.mmdb | head -n 1` /etc/nginx/geoip/db.mmdb

ln -sf /dev/stdout /var/log/nginx/access.log
ln -sf /dev/stderr /var/log/nginx/error.log

crond
exec nginx -g "daemon off;"